[package]
name = "protocol"
version = "0.1.0"
authors = ["LeakyBucket <DamnBigMan@gmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
capnpc = "0.13"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
